on:
    push:
    repository_dispatch:
    schedule:
    - cron: '0 1 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'repository_dispatch'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: curl https://${GITHUB_REPOSITORY%/*}.github.io/common/version.py | python -
        - uses: actions/setup-python@main
          with:
              python-version: ${{env.PY}}
        - run: |
              python -m compileall -b .
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              docker build -t chaowenguo/aiohttp web
              docker push chaowenguo/aiohttp
              docker build -t chaowenguo/chat:aiohttp chat
              docker push chaowenguo/chat:aiohttp
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              ssh -o StrictHostKeyChecking=no -i key ubuntu@20.112.94.147 'sudo docker stop `sudo docker container ls -q`;
              sudo docker system prune -af;
              sudo docker network create backend;
              sudo docker run -d --name redis --net backend -p 6379:6379 -p 16379:16379 redis --cluster-enabled yes;
              sudo docker run -d --name web --net backend chaowenguo/aiohttp;
              sudo docker run -d --name chat --net backend chaowenguo/chat:aiohttp;
              sudo docker run -d --name ingress --net backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/ingress'
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}  
