on:
    push:
    schedule:
    - cron: '0 1 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: curl https://${GITHUB_REPOSITORY%/*}.github.io/common/version.py | python -
        - uses: actions/setup-python@main
          with:
              python-version: ${{env.PY}}
        - run: |
              python -m compileall -b .
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              curl https://raw.githubusercontent.com/${GITHUB_REPOSITORY%/*}/database/main/DigiCertGlobalRootCA.crt.pem > web/DigiCertGlobalRootCA.crt.pem
              docker build -t chaowenguo/aiohttp --build-arg VERSION=${PY%.*} web
              docker push chaowenguo/aiohttp
              docker build -t chaowenguo/chat:aiohttp --build-arg VERSION=${PY%.*} chat
              docker push chaowenguo/chat:aiohttp
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/35.193.116.197.key > key
              chmod 400 key
              ssh -o StrictHostKeyChecking=no -i key ubuntu@35.193.116.197 'sudo docker network create backend;
              sudo docker run -d --name redis --network backend redis;
              sudo docker run -d --name web --network backend chaowenguo/aiohttp;
              sudo docker run -d --name chat --network backend chaowenguo/chat:aiohttp;
              sudo docker run -d --name nginx --network backend -p 443:443 -v /etc/letsencrypt/live/chaowenguo.eu.org:/encrypt:ro chaowenguo/nginx'
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}  
